// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc_locations.Data;

#nullable disable

namespace mvc_locations.Migrations
{
    [DbContext(typeof(LocationContext))]
    [Migration("20220330170121_NewData")]
    partial class NewData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("mvc_locations.Models.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("city_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("country_id")
                        .HasColumnType("int");

                    b.Property<decimal>("latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("longitude")
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("id");

                    b.HasIndex("country_id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            city_name = "Kopenhagen",
                            country_id = 1,
                            latitude = 55.672520m,
                            longitude = 12.563413m
                        },
                        new
                        {
                            id = 2,
                            city_name = "Holstebro",
                            country_id = 1,
                            latitude = 56.362564m,
                            longitude = 8.621231m
                        },
                        new
                        {
                            id = 3,
                            city_name = "Kolding",
                            country_id = 1,
                            latitude = 55.495972m,
                            longitude = 9.473052m
                        },
                        new
                        {
                            id = 4,
                            city_name = "Madrid",
                            country_id = 2,
                            latitude = 40.416775m,
                            longitude = -3.703790m
                        },
                        new
                        {
                            id = 5,
                            city_name = "Barcelona",
                            country_id = 2,
                            latitude = 41.346176m,
                            longitude = 2.168365m
                        },
                        new
                        {
                            id = 6,
                            city_name = "Sevilla",
                            country_id = 2,
                            latitude = 37.392529m,
                            longitude = -5.994072m
                        });
                });

            modelBuilder.Entity("mvc_locations.Models.Country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("country_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("country_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_name_eng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            id = 1,
                            country_code = "+45",
                            country_name = "Danska",
                            country_name_eng = "Denmark"
                        },
                        new
                        {
                            id = 2,
                            country_code = "+34",
                            country_name = "Španjolska",
                            country_name_eng = "Spian"
                        });
                });

            modelBuilder.Entity("mvc_locations.Models.City", b =>
                {
                    b.HasOne("mvc_locations.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("country_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
